<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Droobi Admin Portal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>74755532-b0b0-444c-8b78-b8af9fffba62</testSuiteGuid>
   <testCaseLink>
      <guid>7cf8f67b-2d3c-4cc0-877e-b3134531d902</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login - 1/Verify that not registered user can not log in to droobi admin portal - C668</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e20a2d-6614-4216-bf32-fa7f31f88310</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b53d2449-7d90-44a2-aa63-f9cf672f6ef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8b7b7f3-485b-4793-967e-1efa064ff1ea</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>263134a8-c49b-41d2-87e6-d5762b113e91</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login - 1/Login with valid creds - C1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f91859b-d702-407c-b5e9-635c4a781c31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aea957b-94b1-4bdb-b000-c85ebac063cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1238658-a9de-492b-8068-555168aa45b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>714813fc-d0ec-431f-98f2-86dc2fb20d0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login - 1/Verify that user is able to login if email is entered in Caps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb5d078a-d33a-4fa8-a45d-28a4ab4e956d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d996887-dd44-4c4b-98d3-d0be6dbaee42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>979da30b-e8b0-4b27-ac13-f4a414657e26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3261fac1-c86f-4830-a91d-91e657607dce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login - 1/Validation on email and password fields - C490</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44222a99-adbe-4115-ae2b-9380444ee692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00cd0084-7221-4c48-b784-a4735de2cfd9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
